name: First

on:
  push:
    branches:
      - Feature

env:
  USER_NAME: "Diego Rojas"
  USER_PASSWORD: ${{ secrets.PASSWORD_ACTION }}

jobs:

  greeting:

    runs-on: ubuntu-latest

    steps:
      - name: textos
        run: |
          echo "Hello world! I am ${{ env.USER_NAME }}"
          echo "password: ${{ env.USER_PASSWORD }}"
          echo "My OS is: ${{ runner.os }}"
          echo "My GitHub is: ${{ github.actor }}"
          echo "The name's repository is: ${{ github.repository }}"

  condicionales:

    runs-on: ubuntu-latest

    steps:
      - name: Probando el if
        if: ${{ vars.ANYVARIABLE == 123456 }}
        run: |
          echo "✅ Paso el test"
    
  funciones:

    runs-on: ubuntu-latest

    steps:
      - name: Probando contians
        if: ${{ contains ( github.actor, 'Diego' ) }}
        run: echo "✅ El usuario tiene a Diego"
        
      - name: Probando mostrar si un archivo no exite
        if: ${{ hashFiles( 'package.json' ) == '' }}
        run: echo "🚫 El archivo package.json no existe"