name: First

on:
  push:
    branches:
      - Feature

env:
  USER_NAME: "Diego Rojas"
  USER_PASSWORD: 1234

jobs:

  greeting:

    runs-on: ubuntu-latest

    steps:
      - name: greeting
        run: |
          echo "Hello world! I am ${{ env.USER_NAME }}"
          echo "password: ${{ env.USER_PASSWORD }}"