name: First

on:
  push:
    branches:
      - Clases

env:
  USER_NAME: "Diego Rojas"
  USER_PASSWORD: ${{ secrets.PASSWORD_ACTION }}

jobs:

  greeting:

    runs-on: ubuntu-latest

    steps:
      - name: textos
        run: |
          echo "Hello world! I am ${{ env.USER_NAME }}"
          echo "password: ${{ env.USER_PASSWORD }}"
          echo "My OS is: ${{ runner.os }}"
          echo "My GitHub is: ${{ github.actor }}"
          echo "The name's repository is: ${{ github.repository }}"

  condicionales:

    runs-on: ubuntu-latest

    steps:
      - name: Probando el if
        if: ${{ vars.ANYVARIABLE == 123456 }}
        run: |
          echo "✅ Paso el test"
    
  funciones:

    runs-on: ubuntu-latest

    outputs:
      artifact: ${{ steps.message.outputs.existFile }}

    steps:
      - name: Probando contians
        if: ${{ contains ( github.actor, 'Diego' ) }}
        run: echo "✅ El usuario tiene a Diego"

      - name: Revisa el repositorio
        uses: actions/checkout@v6
        
      - name: Verificar si existe package.json
        id: message
        run: |
          if [ -f package.json ]; then
            echo "existFile=true" >> $GITHUB_OUTPUT
          else
            echo "existFile=false" >> $GITHUB_OUTPUT
          fi

  showFile:

    runs-on: ubuntu-latest
    needs: funciones

    steps:
      - name: Revisa el repositorio
        uses: actions/checkout@v6

      - name: Mostrar el archivo package.json si existe
        if: ${{ needs.funciones.outputs.artifact == 'true' }}
        run: cat ./package.json
