name: Readme-workflow

on: 
  push:
    branches:
      - main
      - Feature

# Permitir los cambios para el repositorio

permissions:
  contents: write

jobs:
  updateVersion:
    runs-on: ubuntu-latest

    steps: 

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: getVersion
        uses: paulhatch/semantic-version@v5.4.0
        id: version
        with:
          tag_prefix: "v"               # Importante agregar que lea el tag, sin él no aumanta más alla de la VERSION: 1.0.0
          major_pattern: "Major:"
          minor_pattern: "Feature:"
          version_format: "${major}.${minor}.${patch}"

      - name: Modificar package.json
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          jq ".version = \"$NEW_VERSION\"" package.json > tmp.json
          mv tmp.json package.json
          cat package.json

      - name: Guardar el commit solo para el README.md
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          sed -i "s/VERSION: .*/VERSION: $NEW_VERSION/" README.md
          cat README.md

      - name: Commit de los cambios
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add package.json README.md
          git commit -m "Cambios actualizados: update version $NEW_VERSION" || echo "No changes"
          git push